FROM php:8.3-fpm

# 🛑 Removed the sed line that changed port 9000 to 9082

WORKDIR /var/www/runnrs

RUN apt-get update && apt-get install -y \
    libzip-dev \
    libpng-dev \
    libjpeg-dev \
    libicu-dev \
    libxslt1-dev \
    libfreetype-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    curl \
    zip \
    unzip

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-configure gd --with-freetype --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd pdo pdo_mysql zip intl xsl

RUN php -r "readfile('https://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer

RUN groupadd -g 1000 www 
RUN useradd -u 1000 -ms /bin/bash -g www www

COPY --chown=www:www . /var/www/runnrs

USER www

CMD ["php-fpm"]
